# Generated by Django 4.1.2 on 2026-08-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('customer_goods_code', models.CharField(blank=True, default='', max_length=255)),
                ('goods_desc', models.CharField(blank=True, default='', max_length=1000)),
                ('expected_qty', models.PositiveIntegerField(default=0)),
                ('actual_qty', models.PositiveIntegerField(default=0)),
                ('accepted_qty', models.PositiveIntegerField(default=0)),
                ('damage_qty', models.PositiveIntegerField(default=0)),
                ('hold_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('putaway_qty', models.PositiveIntegerField(default=0)),
                ('bin_name', models.CharField(blank=True, default='', max_length=255)),
                ('exception_note', models.TextField(blank=True, default='')),
                ('resolution_action', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'receivingdetail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingPutaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('bin_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receivingputaway',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingReconciliationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('operator', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receivingreconciliationevent',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('receipt_no', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('container_tracking', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECEIVING', 'Receiving'), ('QC_PENDING', 'QC pending'), ('QC_EXCEPTION', 'QC exception'), ('PUTAWAY_PENDING', 'Putaway pending'), ('PUTAWAY_COMPLETE', 'Putaway complete'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='RECEIVING', max_length=32)),
                ('reconciliation_status', models.CharField(choices=[('AWAITING_ASN', 'Awaiting customer ASN'), ('PENDING', 'Reconciliation pending'), ('MATCHED', 'Matched'), ('EXCEPTION', 'Reconciliation exception'), ('RESOLVED', 'Variance resolved'), ('DISPUTED', 'Customer dispute')], default='AWAITING_ASN', max_length=32)),
                ('linked_asn_code', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(default='OPERATOR', max_length=32)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('exception_note', models.TextField(blank=True, default='')),
                ('resolution_action', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('qc_by', models.CharField(blank=True, default='', max_length=255)),
                ('putaway_by', models.CharField(blank=True, default='', max_length=255)),
                ('closed_by', models.CharField(blank=True, default='', max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'receivingrecord',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DAMAGED', 'Damaged'), ('WRONG_SKU', 'Wrong SKU'), ('DUPLICATE', 'Duplicate'), ('UNEXPECTED', 'Unexpected'), ('HOLD', 'Hold'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=32)),
                ('scanned_goods_code', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('evidence_url', models.CharField(blank=True, default='', max_length=1000)),
                ('scanned_by', models.CharField(blank=True, default='', max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='receiving.receivingdetail')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='receiving.receivingrecord')),
            ],
            options={
                'db_table': 'receivingserial',
                'ordering': ['goods_code', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='receivingrecord',
            index=models.Index(fields=['openid', 'status'], name='receivingre_openid_ac4acf_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingrecord',
            index=models.Index(fields=['openid', 'reconciliation_status'], name='receivingre_openid_63f147_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingrecord',
            index=models.Index(fields=['openid', 'linked_asn_code'], name='receivingre_openid_f480d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivingrecord',
            constraint=models.UniqueConstraint(fields=('openid', 'receipt_no'), name='receiving_openid_receipt_no_uniq'),
        ),
        migrations.AddField(
            model_name='receivingreconciliationevent',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_events', to='receiving.receivingrecord'),
        ),
        migrations.AddField(
            model_name='receivingputaway',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaways', to='receiving.receivingdetail'),
        ),
        migrations.AddField(
            model_name='receivingputaway',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaways', to='receiving.receivingrecord'),
        ),
        migrations.AddField(
            model_name='receivingdetail',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='receiving.receivingrecord'),
        ),
        migrations.AddIndex(
            model_name='receivingserial',
            index=models.Index(fields=['openid', 'serial_number'], name='receivingse_openid_0139df_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingserial',
            index=models.Index(fields=['receipt', 'goods_code'], name='receivingse_receipt_4d843d_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivingserial',
            constraint=models.UniqueConstraint(fields=('receipt', 'serial_number'), name='receiving_receipt_serial_uniq'),
        ),
        migrations.AddIndex(
            model_name='receivingreconciliationevent',
            index=models.Index(fields=['openid', 'receipt', 'event_type'], name='receivingre_openid_4d2332_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingputaway',
            index=models.Index(fields=['openid', 'receipt'], name='receivingpu_openid_323ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingputaway',
            index=models.Index(fields=['openid', 'bin_name'], name='receivingpu_openid_46287f_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivingputaway',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('openid', 'idempotency_key'), name='receiving_putaway_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='receivingdetail',
            index=models.Index(fields=['openid', 'goods_code'], name='receivingde_openid_27e391_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingdetail',
            index=models.Index(fields=['receipt', 'goods_code'], name='receivingde_receipt_b6a29b_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivingdetail',
            constraint=models.UniqueConstraint(fields=('receipt', 'goods_code'), name='receiving_receipt_goods_uniq'),
        ),
    ]
