# Generated by Django 4.1.2 on 2026-08-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingdetail',
            name='asn_expected_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivingdetail',
            name='asn_stock_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivingdetail',
            name='inventory_qty_applied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
