# Generated by Django 4.1.2 on 2026-08-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_receivingdetail_asn_expected_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingrecord',
            name='putaway_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingrecord',
            name='putaway_assigned_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='receivingrecord',
            name='putaway_driver',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
