# Generated by Django 5.0.14 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.BigIntegerField(db_index=True)),
                ('openid', models.CharField(db_index=True, max_length=255)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_kind', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_session_token',
            },
        ),
        migrations.AddIndex(
            model_name='staffsessiontoken',
            index=models.Index(fields=['staff_id', 'is_revoked'], name='staff_sessi_staff_i_00f639_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsessiontoken',
            index=models.Index(fields=['openid', 'is_revoked'], name='staff_sessi_openid_50fa03_idx'),
        ),
    ]
