# Generated by Django 4.1.2 on 2026-08-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackListDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('asn_code', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Uploaded file'), ('EMAIL', 'Email attachment'), ('GOOGLE_DRIVE', 'Google Drive'), ('MANUAL', 'Manual entry')], default='UPLOAD', max_length=32)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=32)),
                ('has_serials', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packlistdocument',
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='asnserialrecord',
            name='status',
            field=models.CharField(choices=[('EXPECTED', 'Expected'), ('ACCEPTED', 'Accepted'), ('UNEXPECTED', 'Unexpected'), ('DUPLICATE', 'Duplicate'), ('WRONG_SKU', 'Wrong SKU'), ('DAMAGED', 'Damaged'), ('REJECTED', 'Rejected'), ('UNVERIFIED', 'Scanned without Pack List')], default='EXPECTED', max_length=32),
        ),
        migrations.CreateModel(
            name='PackListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('asn_code', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('customer_goods_code', models.CharField(blank=True, default='', max_length=255)),
                ('goods_qty', models.PositiveIntegerField(default=0)),
                ('goods_desc', models.CharField(blank=True, default='', max_length=1000)),
                ('goods_weight', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('goods_volume', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pack_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='asnserial.packlistdocument')),
            ],
            options={
                'db_table': 'packlistline',
                'ordering': ['source_row', 'goods_code', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='packlistdocument',
            index=models.Index(fields=['openid', 'asn_code', 'status'], name='packlistdoc_openid_df3a80_idx'),
        ),
        migrations.AddIndex(
            model_name='packlistdocument',
            index=models.Index(fields=['openid', 'source_type'], name='packlistdoc_openid_444ad5_idx'),
        ),
        migrations.AddField(
            model_name='asnserialrecord',
            name='pack_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_records', to='asnserial.packlistdocument'),
        ),
        migrations.AddIndex(
            model_name='packlistline',
            index=models.Index(fields=['openid', 'asn_code', 'goods_code'], name='packlistlin_openid_8d7b32_idx'),
        ),
        migrations.AddIndex(
            model_name='packlistline',
            index=models.Index(fields=['pack_list', 'goods_code'], name='packlistlin_pack_li_fecd78_idx'),
        ),
    ]
