# Generated by Django 4.1.2 on 2026-08-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0013_source_provenance_web_workflow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entityprovenance',
            index=models.Index(fields=['openid', 'entity_type', 'entity_ref'], name='entityprove_openid_cf78c5_idx'),
        ),
        migrations.AddIndex(
            model_name='entityprovenance',
            index=models.Index(fields=['source', 'field_name'], name='entityprove_source__0bb186_idx'),
        ),
    ]
