# Generated by Django 4.1.2 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0014_entityprovenance_entityprove_openid_cf78c5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceevidence',
            name='mailbox_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sourceevidence',
            name='message_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='sourceevidence',
            name='thread_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='sourceevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__gt', ''), ('mailbox_account__gt', ''), ('message_id__gt', ''), ('source_type', 'EMAIL')), fields=('openid', 'source_type', 'mailbox_account', 'message_id', 'content_hash'), name='sourceevidence_email_message_hash_unique'),
        ),
    ]
