# Generated by Django 4.1.2 on 2026-08-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0015_sourceevidence_mailbox_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('mailbox_account', models.CharField(max_length=255)),
                ('trigger_source', models.CharField(choices=[('CODEX_AUTOMATION', 'Codex Automation'), ('MANUAL', 'Manual')], default='CODEX_AUTOMATION', max_length=32)),
                ('automation_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('cursor_before', models.CharField(blank=True, default='', max_length=1000)),
                ('cursor_after', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('captured_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mailboxsyncrun',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceIntakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('mailbox_account', models.CharField(blank=True, default='', max_length=255)),
                ('operation', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('SUPPORTING', 'Supporting'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('document_type', models.CharField(choices=[('INBOUND_NOTICE', 'Inbound notice'), ('PACK_LIST', 'Pack List'), ('PICK_TICKET', 'Pick Ticket'), ('DELIVERY_REQUEST', 'Delivery request'), ('APPOINTMENT', 'Appointment'), ('QC_SCAN', 'QC / scan sheet'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('status', models.CharField(choices=[('CAPTURED', 'Captured'), ('ANALYZING', 'Analyzing'), ('REVIEW_REQUIRED', 'Review required'), ('READY_FOR_PREVIEW', 'Ready for preview'), ('APPROVAL_REQUIRED', 'Approval required'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed')], default='CAPTURED', max_length=32)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('matched_entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('matched_entity_ref', models.CharField(blank=True, default='', max_length=255)),
                ('owner_role', models.CharField(blank=True, default='', max_length=64)),
                ('next_action', models.CharField(blank=True, default='', max_length=1000)),
                ('exception_summary', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intake_record', to='asnserial.sourceevidence')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_records', to='asnserial.mailboxsyncrun')),
            ],
            options={
                'db_table': 'sourceintakerecord',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceIntakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('actor_type', models.CharField(blank=True, default='', max_length=64)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='asnserial.sourceintakerecord')),
            ],
            options={
                'db_table': 'sourceintakeevent',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('attachment_name', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('content_hash', models.CharField(max_length=64)),
                ('storage_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('storage_size', models.PositiveBigIntegerField(default=0)),
                ('security_status', models.CharField(choices=[('PENDING', 'Pending'), ('STORED', 'Stored'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('source_location', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='asnserial.sourceevidence')),
            ],
            options={
                'db_table': 'sourceattachment',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='mailboxsyncrun',
            index=models.Index(fields=['openid', 'mailbox_account', 'started_at'], name='mailboxsync_openid_3aaae3_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxsyncrun',
            index=models.Index(fields=['openid', 'status', 'started_at'], name='mailboxsync_openid_33fa0c_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakerecord',
            index=models.Index(fields=['openid', 'status', 'updated_at'], name='sourceintak_openid_00aa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakerecord',
            index=models.Index(fields=['openid', 'operation', 'updated_at'], name='sourceintak_openid_e7aac9_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakerecord',
            index=models.Index(fields=['openid', 'mailbox_account', 'received_at'], name='sourceintak_openid_a5d94d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakerecord',
            index=models.Index(fields=['openid', 'matched_entity_type', 'matched_entity_ref'], name='sourceintak_openid_dc5307_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakeevent',
            index=models.Index(fields=['openid', 'intake', 'created_at'], name='sourceintak_openid_1ca5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceintakeevent',
            index=models.Index(fields=['openid', 'status', 'created_at'], name='sourceintak_openid_8baa32_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceattachment',
            index=models.Index(fields=['openid', 'content_hash'], name='sourceattac_openid_3fb23d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceattachment',
            index=models.Index(fields=['source', 'attachment_name'], name='sourceattac_source__c32c02_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceattachment',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='sourceattachment_source_hash_unique'),
        ),
    ]
