# Generated by Django 4.1.2 on 2026-08-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0016_mailboxsyncrun_sourceintakerecord_sourceintakeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('mailbox_account', models.CharField(max_length=255)),
                ('cursor', models.CharField(blank=True, default='', max_length=1000)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='asnserial.mailboxsyncrun')),
                ('last_successful_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='asnserial.mailboxsyncrun')),
            ],
            options={
                'db_table': 'mailboxsyncstate',
            },
        ),
        migrations.AddIndex(
            model_name='mailboxsyncstate',
            index=models.Index(fields=['openid', 'mailbox_account'], name='mailboxsync_openid_8fa6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxsyncstate',
            index=models.Index(fields=['openid', 'lease_expires_at'], name='mailboxsync_openid_5c8535_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailboxsyncstate',
            constraint=models.UniqueConstraint(fields=('openid', 'mailbox_account'), name='mailboxsyncstate_tenant_account_unique'),
        ),
    ]
