# Generated by Django 4.1.2 on 2026-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0017_mailboxsyncstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceevidence',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
