# Generated by Django 4.1.2 on 2026-08-25

import hashlib
import re

from django.db import migrations, models
from django.db.models import Q


def _task_ref(source, operation, external_reference):
    prefix = {
        'INBOUND': 'IB',
        'OUTBOUND': 'OB',
        'SUPPORTING': 'SUP',
        'UNKNOWN': 'MAIL',
    }.get(operation, 'MAIL')
    reference = re.sub(r'[^A-Za-z0-9]+', '-', str(external_reference or '')[:180]).strip('-').upper()[:120]
    if not reference:
        seed = '|'.join([
            source.openid,
            source.thread_id or '',
            source.message_id or '',
            source.content_hash or '',
        ])
        reference = 'MAIL-' + hashlib.sha256(seed.encode('utf-8')).hexdigest()[:12].upper()
    return '%s-%s' % (prefix, reference)


def populate_mail_tasks(apps, schema_editor):
    SourceEvidence = apps.get_model('asnserial', 'SourceEvidence')
    SourceIntakeRecord = apps.get_model('asnserial', 'SourceIntakeRecord')
    MailTask = apps.get_model('asnserial', 'MailTask')
    MailTaskEvent = apps.get_model('asnserial', 'MailTaskEvent')

    role_map = {
        'SUPERVISOR': 'SUPERVISOR',
        'WMS_OPERATOR': 'WMS_OPERATOR',
        'SITE_OPERATOR': 'SITE_OPERATOR',
    }
    status_map = {
        'APPROVAL_REQUIRED': 'AWAITING_SUNNY_APPROVAL',
        'COMPLETED': 'COMPLETED',
        'BLOCKED': 'BLOCKED',
    }
    for record in SourceIntakeRecord.objects.all().iterator():
        source = SourceEvidence.objects.get(id=record.source_id)
        operation = record.operation if record.operation in {'INBOUND', 'OUTBOUND', 'SUPPORTING', 'UNKNOWN'} else 'UNKNOWN'
        role = role_map.get(record.owner_role, 'SUPERVISOR' if operation in {'SUPPORTING', 'UNKNOWN'} else 'WMS_OPERATOR')
        status = status_map.get(record.status, 'OPEN')
        task, created = MailTask.objects.get_or_create(
            openid=record.openid,
            task_ref=_task_ref(source, operation, record.external_reference),
            defaults={
                'operation': operation,
                'subject': record.subject[:1000],
                'external_reference': record.external_reference[:255],
                'status': status,
                'assigned_role': role,
                'next_action': record.next_action[:1000] or 'Maggie: review the email and prepare the WMS handoff.',
                'wms_handoff_status': 'TO_SUNNY' if role == 'SUPERVISOR' else 'TO_MAGGIE',
            },
        )
        if record.task_id != task.id:
            record.task_id = task.id
            record.save(update_fields=['task'])
        if created:
            MailTaskEvent.objects.create(
                task=task,
                source_evidence=source,
                openid=task.openid,
                action='MIGRATED',
                to_status=task.status,
                actor_role=task.assigned_role,
                note='Task created from the existing Source Intake record.',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0018_sourceevidence_sent_at_sourceintakerecord_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('task_ref', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('SUPPORTING', 'Supporting'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_SUNNY_APPROVAL', 'Awaiting Sunny approval'), ('READY_FOR_MARK', 'Ready for Mark'), ('SITE_IN_PROGRESS', 'Site work in progress'), ('WMS_FINALIZATION', 'Awaiting Maggie WMS update'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='OPEN', max_length=32)),
                ('assigned_role', models.CharField(choices=[('SUPERVISOR', 'Sunny / Supervisor'), ('WMS_OPERATOR', 'Maggie / WMS operator'), ('SITE_OPERATOR', 'Mark / Site operator')], default='WMS_OPERATOR', max_length=32)),
                ('assigned_staff_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('assigned_staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('next_action', models.CharField(blank=True, default='', max_length=1000)),
                ('wms_handoff_status', models.CharField(choices=[('TO_MAGGIE', 'To Maggie'), ('TO_SUNNY', 'To Sunny'), ('TO_MARK', 'To Mark'), ('SITE_IN_PROGRESS', 'Mark is working'), ('RETURNED_TO_MAGGIE', 'Returned to Maggie'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='TO_MAGGIE', max_length=32)),
                ('wms_entity_system', models.CharField(blank=True, choices=[('LEGACY_PROD', 'Legacy production'), ('MIGRATED', 'Migrated GreaterWMS')], default='', max_length=32)),
                ('wms_entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('wms_entity_ref', models.CharField(blank=True, default='', max_length=255)),
                ('wms_handoff_note', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mailtask',
                'ordering': ['-updated_at', '-id'],
                'indexes': [
                    models.Index(fields=['openid', 'status', 'updated_at'], name='mailtask_openid_d96a78_idx'),
                    models.Index(fields=['openid', 'assigned_role', 'status'], name='mailtask_openid_edba2a_idx'),
                    models.Index(fields=['openid', 'wms_handoff_status', 'updated_at'], name='mailtask_openid_b3abf4_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MailTaskApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('approval_type', models.CharField(choices=[('OUTBOUND_FINAL', 'Outbound final approval')], default='OUTBOUND_FINAL', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('requested_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='approvals', to='asnserial.mailtask')),
            ],
            options={
                'db_table': 'mailtaskapproval',
                'ordering': ['-requested_at', '-id'],
                'indexes': [
                    models.Index(fields=['openid', 'status', 'requested_at'], name='mailtaskapp_openid_433313_idx'),
                    models.Index(fields=['task', 'approval_type', 'requested_at'], name='mailtaskapp_task_id_8c96c6_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MailTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('actor_role', models.CharField(blank=True, default='', max_length=32)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='mailtask_events', to='asnserial.sourceevidence')),
                ('task', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='task_events', to='asnserial.mailtask')),
            ],
            options={
                'db_table': 'mailtaskevent',
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['openid', 'task', 'created_at'], name='mailtaskeve_openid_0ba5fa_idx'),
                    models.Index(fields=['openid', 'action', 'created_at'], name='mailtaskeve_openid_f4e1dc_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='intake_records', to='asnserial.mailtask'),
        ),
        migrations.AddConstraint(
            model_name='mailtask',
            constraint=models.UniqueConstraint(fields=('openid', 'task_ref'), name='mailtask_tenant_task_ref_unique'),
        ),
        migrations.AddConstraint(
            model_name='mailtaskapproval',
            constraint=models.UniqueConstraint(condition=Q(('status', 'PENDING')), fields=('task', 'status'), name='mailtask_one_pending_approval'),
        ),
        migrations.RunPython(populate_mail_tasks, migrations.RunPython.noop),
    ]
