# Generated by Django 4.1.2 on 2026-08-26

import re
from datetime import datetime, time
from zoneinfo import ZoneInfo

from django.db import migrations, models


MAIL_FLOW_CHOICES = (
    ('CLIENT_TO_LOGISTICS', 'Client to Peak Logistics'),
    ('EXTERNAL_TO_LOGISTICS', 'External service to Peak Logistics'),
    ('LOGISTICS_TO_WAREHOUSE', 'Peak Logistics to Warehouse'),
    ('WAREHOUSE_TO_LOGISTICS', 'Warehouse to Peak Logistics'),
    ('LOGISTICS_TO_EXTERNAL', 'Peak Logistics to External service'),
    ('WAREHOUSE_TO_EXTERNAL', 'Warehouse to External service'),
    ('INTERNAL', 'Internal coordination'),
    ('REVIEW', 'Review direction'),
)

MAIL_TIME_PRECISION_CHOICES = (
    ('EXACT', 'Exact time'),
    ('DATE_ONLY', 'Date only'),
    ('UNKNOWN', 'Unknown'),
)

MAILBOX_TIME_ZONE = ZoneInfo('America/Chicago')


def _first(package, *keys):
    if not isinstance(package, dict):
        return ''
    for key in keys:
        value = package.get(key)
        if value not in (None, ''):
            return value
    return ''


def _metadata_value(metadata, *keys):
    original = {}
    if isinstance(metadata, dict):
        for key in ('original_email', 'nested_email', 'original_source', 'original'):
            if isinstance(metadata.get(key), dict):
                original = metadata[key]
                break
    return _first(original, *keys) or _first(metadata, *keys)


def _mail_datetime(value):
    raw = str(value or '').strip()
    if not raw:
        return None
    parsed = None
    try:
        parsed = datetime.fromisoformat(raw.replace('Z', '+00:00'))
    except (TypeError, ValueError):
        try:
            parsed = datetime.combine(datetime.strptime(raw, '%Y-%m-%d').date(), time.min)
        except (TypeError, ValueError):
            return None
    if parsed.tzinfo is not None:
        return parsed.astimezone(MAILBOX_TIME_ZONE).replace(tzinfo=None)
    return parsed


def _precision(value, explicit=''):
    explicit = str(explicit or '').strip().upper()
    if explicit in {'EXACT', 'DATE_ONLY', 'UNKNOWN'}:
        return explicit
    raw = str(value or '').strip()
    if re.match(r'^\d{4}[-/]\d{1,2}[-/]\d{1,2}$', raw) or re.match(r'^\d{4}年\d{1,2}月\d{1,2}日$', raw):
        return 'DATE_ONLY'
    return 'EXACT' if _mail_datetime(raw) is not None else 'UNKNOWN'


def _flow(metadata):
    raw = _metadata_value(metadata, 'mail_flow', 'message_flow', 'email_flow', 'flow')
    normalized = str(raw or '').upper().replace('→', '->')
    normalized = re.sub(r'\s*->\s*', '->', normalized)
    normalized = re.sub(r'\s+', '_', normalized).replace(' ', '_')
    aliases = {
        'CLIENT_TO_LOGISTICS': 'CLIENT_TO_LOGISTICS',
        'CLIENT_TO_LOG': 'CLIENT_TO_LOGISTICS',
        'CLIENT->LOGISTICS': 'CLIENT_TO_LOGISTICS',
        'CLIENT->LOG': 'CLIENT_TO_LOGISTICS',
        'EXTERNAL_TO_LOGISTICS': 'EXTERNAL_TO_LOGISTICS',
        'EXTERNAL_SERVICE_TO_LOGISTICS': 'EXTERNAL_TO_LOGISTICS',
        'EXTERNAL->LOGISTICS': 'EXTERNAL_TO_LOGISTICS',
        'EXTERNAL->LOG': 'EXTERNAL_TO_LOGISTICS',
        'LOGISTICS_TO_WAREHOUSE': 'LOGISTICS_TO_WAREHOUSE',
        'LOGISTICS_TO_WH': 'LOGISTICS_TO_WAREHOUSE',
        'LOGISTICS->WAREHOUSE': 'LOGISTICS_TO_WAREHOUSE',
        'LOGISTICS->WH': 'LOGISTICS_TO_WAREHOUSE',
        'WAREHOUSE_TO_LOGISTICS': 'WAREHOUSE_TO_LOGISTICS',
        'WAREHOUSE_TO_LOG': 'WAREHOUSE_TO_LOGISTICS',
        'WAREHOUSE->LOGISTICS': 'WAREHOUSE_TO_LOGISTICS',
        'WAREHOUSE->LOG': 'WAREHOUSE_TO_LOGISTICS',
        'LOGISTICS_TO_EXTERNAL': 'LOGISTICS_TO_EXTERNAL',
        'LOGISTICS_TO_EXT': 'LOGISTICS_TO_EXTERNAL',
        'LOGISTICS->EXTERNAL': 'LOGISTICS_TO_EXTERNAL',
        'LOGISTICS->EXT': 'LOGISTICS_TO_EXTERNAL',
        'WAREHOUSE_TO_EXTERNAL': 'WAREHOUSE_TO_EXTERNAL',
        'WAREHOUSE_TO_EXT': 'WAREHOUSE_TO_EXTERNAL',
        'WAREHOUSE->EXTERNAL': 'WAREHOUSE_TO_EXTERNAL',
        'WAREHOUSE->EXT': 'WAREHOUSE_TO_EXTERNAL',
        'INTERNAL': 'INTERNAL',
        'INTERNAL_COORDINATION': 'INTERNAL',
        'REVIEW': 'REVIEW',
        'REVIEW_DIRECTION': 'REVIEW',
    }
    if normalized in aliases:
        return aliases[normalized]
    return 'REVIEW'


def _schedule(metadata):
    due_raw = _metadata_value(metadata, 'due_at', 'deadline_at', 'due', 'deadline')
    event_raw = _metadata_value(metadata, 'event_at', 'business_event_at', 'event_time', 'event')
    return {
        'flow': _flow(metadata),
        'due_at': _mail_datetime(due_raw),
        'due_type': str(_metadata_value(metadata, 'due_type', 'deadline_type') or '').strip().upper()[:32],
        'due_precision': _precision(due_raw, _metadata_value(metadata, 'due_precision', 'deadline_precision')),
        'event_at': _mail_datetime(event_raw),
        'event_type': str(_metadata_value(metadata, 'event_type', 'business_event_type') or '').strip().upper()[:32],
        'event_precision': _precision(event_raw, _metadata_value(metadata, 'event_precision', 'business_event_precision')),
    }


def _backfill_mailtask_fields(apps, schema_editor):
    SourceEvidence = apps.get_model('asnserial', 'SourceEvidence')
    SourceIntakeRecord = apps.get_model('asnserial', 'SourceIntakeRecord')
    MailTask = apps.get_model('asnserial', 'MailTask')

    for source in SourceEvidence.objects.all().iterator():
        metadata = source.metadata if isinstance(source.metadata, dict) else {}
        sent_raw = _metadata_value(metadata, 'sent_at', 'email_sent_at')
        received_raw = _metadata_value(metadata, 'received_at', 'email_received_at')
        sent_at = _mail_datetime(sent_raw)
        if sent_at is not None and source.sent_at != sent_at:
            source.sent_at = sent_at
            source.save(update_fields=['sent_at'])
        record = SourceIntakeRecord.objects.filter(source_id=source.id).first()
        if record is None:
            continue
        values = _schedule(metadata)
        values['sent_at'] = sent_at or record.sent_at
        values['received_at'] = _mail_datetime(received_raw) or record.received_at
        for field, value in values.items():
            setattr(record, field, value)
        record.save(update_fields=list(values.keys()))

    for task in MailTask.objects.all().iterator():
        record = task.intake_records.order_by('-updated_at', '-id').first()
        if record is None:
            continue
        task.flow = record.flow or 'REVIEW'
        task.due_at = record.due_at
        task.due_type = record.due_type
        task.due_precision = record.due_precision
        task.event_at = record.event_at
        task.event_type = record.event_type
        task.event_precision = record.event_precision
        known_times = [value for value in (record.sent_at, record.received_at) if value is not None]
        task.last_mail_at = max(known_times) if known_times else None
        task.save(update_fields=[
            'flow', 'due_at', 'due_type', 'due_precision', 'event_at',
            'event_type', 'event_precision', 'last_mail_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('asnserial', '0019_mailtask_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceintakerecord',
            name='flow',
            field=models.CharField(choices=MAIL_FLOW_CHOICES, default='REVIEW', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='due_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='due_precision',
            field=models.CharField(choices=MAIL_TIME_PRECISION_CHOICES, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceintakerecord',
            name='event_precision',
            field=models.CharField(choices=MAIL_TIME_PRECISION_CHOICES, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='flow',
            field=models.CharField(choices=MAIL_FLOW_CHOICES, default='REVIEW', max_length=32),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='due_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='due_precision',
            field=models.CharField(choices=MAIL_TIME_PRECISION_CHOICES, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='event_precision',
            field=models.CharField(choices=MAIL_TIME_PRECISION_CHOICES, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='mailtask',
            name='last_mail_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_mailtask_fields, migrations.RunPython.noop),
    ]
