from django.urls import path

from . import views


urlpatterns = [
    path('records/', views.SerialRecordsView.as_view(), name='asn-serial-records'),
    path('exceptions/', views.SerialExceptionsView.as_view(), name='asn-serial-exceptions'),
    path('exceptions/resolve/', views.SerialExceptionResolveView.as_view(), name='asn-serial-exception-resolve'),
    path('exceptions/move/', views.SerialExceptionMoveView.as_view(), name='asn-serial-exception-move'),
    path('exceptions/resolve-quantity/', views.QuantityExceptionResolveView.as_view(), name='asn-quantity-exception-resolve'),
    path('exceptions/move-quantity/', views.QuantityExceptionMoveView.as_view(), name='asn-quantity-exception-move'),
    path('summary/', views.SerialSummaryView.as_view(), name='asn-serial-summary'),
    path('expected/', views.ExpectedSerialView.as_view(), name='asn-serial-expected'),
    path('scan/', views.ScanSerialView.as_view(), name='asn-serial-scan'),
    path('packlists/', views.PackListListView.as_view(), name='asn-pack-list-list'),
    path('packlists/create/', views.PackListCreateView.as_view(), name='asn-pack-list-create'),
    path('packlists/preview/', views.PackListPreviewView.as_view(), name='asn-pack-list-preview'),
    path('packlists/import/', views.PackListImportView.as_view(), name='asn-pack-list-import'),
    path('packlists/confirm/', views.PackListConfirmView.as_view(), name='asn-pack-list-confirm'),
    path('import/', views.SerialImportView.as_view(), name='asn-serial-import'),
    path('inspections/import/', views.SerialImportView.as_view(), {'inspection': True}, name='asn-serial-inspection-import'),
    path('inspections/preview/', views.SerialImportPreviewView.as_view(), {'inspection': True}, name='asn-serial-inspection-preview'),
    path('import/preview/', views.SerialImportPreviewView.as_view(), name='asn-serial-import-preview'),
    path('inspections/', views.InspectionBatchListView.as_view(), name='asn-serial-inspection-list'),
    path('agent/preview/', views.AgentCommandPreviewView.as_view(), name='asn-agent-command-preview'),
    path('agent/preview/<int:pk>/approve/', views.AgentCommandApproveView.as_view(), name='asn-agent-command-approve'),
    path('sources/capture/', views.SourceCaptureView.as_view(), name='source-evidence-capture'),
    path('sources/', views.SourceEvidenceListView.as_view(), name='source-evidence-list'),
    path('sources/audits/', views.OperationAuditListView.as_view(), name='operation-audit-list'),
    path('intake/', views.SourceIntakeListView.as_view(), name='source-intake-list'),
    path('intake/task-actors/', views.MailTaskActorsView.as_view(), name='mailtask-actors'),
    path('intake/statistics/', views.MailTaskStatisticsView.as_view(), name='mailtask-statistics'),
    path('intake/sync-runs/', views.MailboxSyncRunCreateView.as_view(), name='mailbox-sync-run-create'),
    path('intake/sync-state/', views.MailboxSyncStateView.as_view(), name='mailbox-sync-state'),
    path('intake/sync-runs/<int:pk>/complete/', views.MailboxSyncRunCompleteView.as_view(), name='mailbox-sync-run-complete'),
    path('intake/<int:pk>/assign/', views.MailTaskAssignView.as_view(), name='mailtask-assign'),
    path('intake/<int:pk>/action/', views.MailTaskActionView.as_view(), name='mailtask-action'),
    path('intake/<int:pk>/', views.SourceIntakeDetailView.as_view(), name='source-intake-detail'),
    path('intake/<int:pk>/update/', views.SourceIntakeUpdateView.as_view(), name='source-intake-update'),
    path('web/preview/', views.WebWorkflowPreviewView.as_view(), name='web-workflow-preview'),
    path('web/preview/<int:pk>/approve/', views.WebWorkflowApproveView.as_view(), name='web-workflow-approve'),
]
