# Generated by Django 4.2.20 on 2026-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0002_delivery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnlistmodel',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled At'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='canceled_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Canceled By'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='cancellation_note',
            field=models.TextField(blank=True, default='', verbose_name='Cancellation Note'),
        ),
    ]
