# Generated by Django 4.1.2 on 2026-08-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0003_dnlist_cancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnSerialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('dn_code', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PICKED', 'Picked'), ('IN_TRANSIT', 'In transit'), ('SHIPPED', 'Shipped'), ('RELEASED', 'Released')], default='REQUESTED', max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dnserialallocation',
                'ordering': ['goods_code', 'serial_number'],
            },
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='picked_serials',
            field=models.JSONField(default=list, verbose_name='Picked Serial Numbers'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='requested_serials',
            field=models.JSONField(default=list, verbose_name='Requested Serial Numbers'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='shipped_serials',
            field=models.JSONField(default=list, verbose_name='Shipped Serial Numbers'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='picking_mode',
            field=models.CharField(choices=[('SKU_QTY', 'SKU and quantity'), ('SN', 'Serial number')], default='SKU_QTY', max_length=16, verbose_name='Picking Mode'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='ship_to',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Ship To'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='transport_order_no',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transport Order'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='transport_required',
            field=models.BooleanField(default=False, verbose_name='Transport Required'),
        ),
        migrations.AddIndex(
            model_name='dnserialallocation',
            index=models.Index(fields=['openid', 'serial_number', 'status'], name='dnserialall_openid_08400b_idx'),
        ),
        migrations.AddIndex(
            model_name='dnserialallocation',
            index=models.Index(fields=['openid', 'dn_code', 'goods_code'], name='dnserialall_openid_f9443f_idx'),
        ),
        migrations.AddConstraint(
            model_name='dnserialallocation',
            constraint=models.UniqueConstraint(fields=('openid', 'dn_code', 'serial_number'), name='dn_serial_allocation_uniq'),
        ),
    ]
