# Generated by Django 4.1.2 on 2026-08-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0004_dnserialallocation_dndetailmodel_picked_serials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndetailmodel',
            name='cancelled_qty',
            field=models.BigIntegerField(default=0, verbose_name='Cancelled QTY'),
        ),
    ]
