# Generated by Django 4.1.2 on 2026-08-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0005_dndetailmodel_cancelled_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndetailmodel',
            name='returned_qty',
            field=models.BigIntegerField(default=0, verbose_name='Returned QTY'),
        ),
        migrations.AlterField(
            model_name='dnserialallocation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PICKED', 'Picked'), ('IN_TRANSIT', 'In transit'), ('SHIPPED', 'Shipped'), ('RELEASED', 'Released'), ('RETURNED', 'Returned')], default='REQUESTED', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='dnserialallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'PICKED', 'IN_TRANSIT', 'SHIPPED', 'RELEASED'])), fields=('openid', 'serial_number'), name='dn_serial_allocation_active_uniq'),
        ),
    ]
