# Generated by Django 4.1.2 on 2026-08-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingassignment',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('ACTIVE', 'Occupied'), ('RELEASED', 'Released')], default='RESERVED', max_length=12),
        ),
    ]
