# Generated by Django 4.1.2 on 2026-08-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('transport_no', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=16)),
                ('reference_type', models.CharField(blank=True, default='', max_length=32)),
                ('reference_no', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_location', models.CharField(blank=True, default='', max_length=1000)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=1000)),
                ('carrier', models.CharField(blank=True, default='', max_length=255)),
                ('truck_plate', models.CharField(blank=True, default='', max_length=64)),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('logistics_coordinator', models.CharField(blank=True, default='', max_length=255)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('DRIVER_ASSIGNED', 'Driver assigned'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('pod_reference', models.CharField(blank=True, default='', max_length=255)),
                ('pod_note', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transportorder',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['openid', 'status'], name='transportor_openid_204ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['openid', 'reference_type', 'reference_no'], name='transportor_openid_a71086_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['openid', 'driver_name'], name='transportor_openid_8371e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportorder',
            constraint=models.UniqueConstraint(fields=('openid', 'transport_no'), name='transport_openid_no_uniq'),
        ),
    ]
